# Generated by Django 5.2.15 on 2026-06-30 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('book_type', models.CharField(choices=[('OFFICIAL', 'كتاب رسمي'), ('INCOMING', 'كتاب وارد'), ('OUTGOING', 'كتاب صادر'), ('CIRCULAR', 'تعميم'), ('REVIEW', 'مطالعة')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('priority', models.CharField(choices=[('NORMAL', 'عادية'), ('IMPORTANT', 'مهمة'), ('URGENT', 'عاجلة')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'متبقي'), ('DONE', 'منجز'), ('DEFERRED', 'مؤجل')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
    ]
