# Generated by Django 5.2.15 on 2026-06-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('SECTION_HEAD', 'Section Head'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], default='EMPLOYEE', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('email_for_alerts', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('first_school', models.CharField(blank=True, max_length=150)),
                ('birth_city', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
