# Generated by Django 5.2.15 on 2026-06-30 17:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('meeting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('meeting_time', models.TimeField(default=datetime.time(10, 0))),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('OPEN', 'قادم'), ('DONE', 'منجز'), ('DEFERRED', 'مؤجل'), ('CANCELLED', 'ملغى')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting_date', 'meeting_time'],
            },
        ),
    ]
