# Generated by Django 5.2.15 on 2026-06-30 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('open_tasks', models.PositiveIntegerField(default=0)),
                ('deferred_tasks', models.PositiveIntegerField(default=0)),
                ('urgent_tasks', models.PositiveIntegerField(default=0)),
                ('important_tasks', models.PositiveIntegerField(default=0)),
                ('normal_tasks', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('user', 'report_date')},
            },
        ),
    ]
