# Generated by Django 5.2.15 on 2026-06-30 17:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('task_type', models.CharField(choices=[('REVIEW', 'مطالعة'), ('OFFICIAL_BOOK', 'كتاب رسمي'), ('INCOMING', 'كتاب وارد'), ('OUTGOING', 'كتاب صادر'), ('CIRCULAR', 'تعميم'), ('DISCUSSION', 'مداولة'), ('MEETING', 'اجتماع'), ('OTHER', 'نشاط آخر')], default='OTHER', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('priority', models.CharField(choices=[('NORMAL', 'عادية'), ('IMPORTANT', 'مهمة'), ('URGENT', 'عاجلة')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'متبقية'), ('DONE', 'منجزة'), ('DEFERRED', 'مؤجلة'), ('CANCELLED', 'ملغاة')], default='OPEN', max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_time', models.TimeField(default=datetime.time(9, 0))),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'due_time', '-created_at'],
            },
        ),
    ]
